all:
	$(MAKE) -C adalib all
	$(MAKE) -C bindings all
	$(MAKE) -C gplimports all
	$(MAKE) -C tests all
	$(MAKE) -C utils all
	$(MAKE) -C ihexutil all

clean:
	$(MAKE) -C adalib clean
	$(MAKE) -C bindings clean
	$(MAKE) -C gplimports clean
	$(MAKE) -C tests clean
	$(MAKE) -C utils clean
	$(MAKE) -C ihexutil clean

