all:
	$(MAKE) -C adalib all
	$(MAKE) -C bindings all
	$(MAKE) -C gplimports all
	$(MAKE) -C tests all
	$(MAKE) -C utils all
	$(MAKE) -C ihexutil all
	$(MAKE) -C queue/client all
	$(MAKE) -C queue/manager all

clean:
	$(MAKE) -C adalib clean
	$(MAKE) -C bindings clean
	$(MAKE) -C gplimports clean
	$(MAKE) -C tests clean
	$(MAKE) -C utils clean
	$(MAKE) -C ihexutil clean
	$(MAKE) -C queue/client clean
	$(MAKE) -C queue/manager clean

