all:
	gprbuild -p -P complex_unit_test
	gprbuild -p -P numbers_unit_test
	gprbuild -p -P integrate_unit_test
clean:
	gprclean -P complex_unit_test
	gprclean -P numbers_unit_test
	gprclean -P integrate_unit_test
