all:
	gprbuild -p -P crc16test.gpr
	gprbuild -p -P factors_test.gpr
	gprbuild -p -P testlogging.gpr
	gprbuild -p -P zlibtest.gpr

clean:
	gprclean -P crc16test.gpr
	gprclean -P factors_test.gpr
	gprclean -P testlogging.gpr
	gprclean -P zlibtest.gpr

